import { createContext } from 'react'

type UserContextType = {
    name: string,
    setName: (name: string) => void,
    email: string,
    setEmail: (email: string) => void,
    zipcode: string,
    setZipcode: (zipcode: string) => void,
    phone: string,
    setPhone: (phone: string) => void,
    submitForm: boolean,
    setSubmitForm: (submitForm: boolean) => void,
    location: object,
    setLocation: (location: object) => void,
    openChatbot: boolean,
    setOpenChatbot: (openChatbot: boolean) => void,
    userMessage: string[],
    setUserMessage: (userMessage: string[]) => void,
    inputPrompt: string,
    setInputPrompt: (inputPrompt: string) => void,
    recentPrompt: string,
    setRecentPrompt: (recentPrompt: string) => void,
    showResult: boolean,
    setShowResult: (showResult: boolean) => void,
    loading: boolean,
    setLoading: (loading: boolean) => void,
    resultData: string,
    setResultData: (resultData: string) => void,
    onSent: (prompt?: string) => void,
    messages: Array<{ sender: string, content: string }>
}

const UserContext = createContext<UserContextType>({
    name: '',
    setName: () => { },
    email: '',
    setEmail: () => { },
    zipcode: '',
    setZipcode: () => { },
    phone: '',
    setPhone: () => { },
    submitForm: false,
    setSubmitForm: () => { },
    location: {},
    setLocation: () => { },
    openChatbot: false,
    setOpenChatbot: () => { },
    userMessage: [],
    setUserMessage: () => { },
    inputPrompt: '',
    setInputPrompt: () => { },
    recentPrompt: '',
    setRecentPrompt: () => { },
    showResult: false,
    setShowResult: () => { },
    loading: false,
    setLoading: () => { },
    resultData: '',
    setResultData: () => { },
    onSent: () => { },
    messages: []
})

export default UserContext